namespace WTT.Campaigns.Client.Authoring.Views;

internal static class EditorToolHelp
{
    internal static string For(string id, string caption) =>
        id switch
        {
            "Name" or "MapName" => "Display name of the selected record.",
            "Search" => "Filter this window by name or identifier.",
            "AddBox" => "Create a box-shaped zone. Adjust its dimensions in Properties.",
            "AddSphere" => "Create a spherical zone. Adjust its radius in Properties.",
            "AddMinefield" => "Create a minefield area in the current map.",
            "AddClaymore" => "Place a directional claymore hazard in the current map.",
            "AddSniper" => "Create an out-of-bounds sniper area in the current map.",
            "AddBarbedWire" => "Place a barbed-wire hazard in the current map.",
            "ZoneCreateScope" => "Choose whether new zones belong to the current layout or are shared across the map.",
            "ZoneScope" => "Choose the owner of this zone: the current layout or Shared for map-wide use.",
            "ZoneUses" => "Choose one or more zone types. Select a type again to disable it.",
            "Radius" => "Radius of the selected spherical volume, in metres.",
            "SniperPlaySound" => "Enable or disable audible sniper shots for this hazard.",
            "SniperSuppressed" => "Choose whether sniper shot sounds are suppressed.",
            "Capture" => "Capture the current viewpoint for authoring.",
            "Pick" => "Arm scene picking, then click an object in the world.",
            "MapNew" => "Create a layout for the loaded map.",
            "MapStart" => "Set the route's start marker.",
            "MapCheckpoint" => "Add an ordered checkpoint to the selected route.",
            "MapExit" => "Set the route's exit marker.",
            "MapBarrier" => "Create an invisible physical barrier in the current layout.",
            "MapMoveObject" => "Record a position or rotation change for a scene prop.",
            "MapCopyObject" => "Create an authored copy of a scene prop.",
            "MapHideObject" => "Hide a scene prop through the current layout.",
            "MapDoor" => "Record a door state for the current layout.",
            "MapShape" => "Cycle the selected volume between supported shapes.",
            "MapEarlier" => "Move this checkpoint one place earlier in the route.",
            "MapLater" => "Move this checkpoint one place later in the route.",
            "MapWalkStart" => "Toggle starting the walkthrough from the selected route marker.",
            "RouteFrame" or "SceneFrame" => "Move the editor camera to frame the selection (F).",
            "MapAtPlayer" => "Move the selection to the ground beneath the editor camera.",
            "AtAim" => "Place the selection at the camera's aim point.",
            "MapRebind" or "SceneRebind" => "Associate this saved edit with the currently picked scene object.",
            "Duplicate" or "MapCopy" => "Create a separate copy of the selected record.",
            "Delete" or "MapDelete" => "Delete the selected authored record.",
            "RecordDetailsToggle" or "MapDetailsToggle" => "Show or hide identifiers and technical details for the selection.",
            "Parent" => "Select the parent of the currently picked scene object.",
            "UseObject" => "Use the picked scene object as this event's target.",
            "EventKind" => "Cycle the event type for the selected binding.",
            "SceneCatalog" => "Browse objects available to place in the map.",
            "SceneExisting" => "Browse existing objects in the loaded scene.",
            "SceneChanges" => "Review scene edits saved in the current layout.",
            "SceneSource" => "Filter the catalog by asset source.",
            "SceneFilter" => "Filter by object type. Each Scene tab remembers its own filter.",
            "CatalogGrid" => "Browse catalog items as thumbnail tiles.",
            "CatalogList" => "Browse catalog items in a compact list.",
            "ScenePreviewRetry" => "Retry loading the selected object's preview.",
            "SceneAnchor" => "Cycle the placement anchor for the selected object.",
            "ScenePlace" => "Begin placing the selected catalog object in the world.",
            "SceneRepeat" => "Keep placing copies until Escape, then inspect the last placed object. Each placement can be undone separately.",
            "SceneMove" => "Activate the movement handles for this object (W).",
            "SceneRotate" => "Activate the rotation handles for this object (E).",
            "SceneScale" => "Activate scale handles when the selected object supports scaling (R).",
            "SceneRemove" => "Remove the selected object through the current layout.",
            "SceneRestore" => "Discard this scene edit and restore the object's original state.",
            "Previous" => "Show the previous page of results.",
            "Next" => "Show the next page of results.",
            "AiEncounter" => "Create an encounter containing an activation trigger and waves.",
            "AiWave" => "Add a wave to the encounter selected in the tree.",
            "AiRoster" => "Add a bot roster to the wave selected in the tree.",
            "AiSpawn" => "Create a spawn point, then assign it to a bot roster.",
            "AiPatrol" => "Create a patrol route, then add waypoints and assign it to a roster.",
            "AiWaypoint" => "Add a waypoint to the patrol route selected in the tree.",
            "AiNavigation" => "Toggle the navigation inspection overlay for authored spawn points and routes.",
            "AiSimulate" => "Trigger the selected encounter, wave or roster during an active preview.",
            "AiReset" => "Reset the encounter preview so its triggers can run again.",
            "AiTrigger" => "Cycle how the encounter activates: mission start, event or player entry.",
            "AiTriggerEventId" => "Event identifier that activates this encounter. Use manual for explicit preview triggering.",
            "AiTriggerZoneId" => "Identifier of the zone the player must enter to activate this encounter.",
            "AiWaveDelaySeconds" => "Delay before this wave begins, in seconds.",
            "AiWaveWaitPrevious" => "Cycle whether the wave waits for the previous wave.",
            "AiRosterRole" => "Cycle the bot role used by this roster.",
            "AiRosterDifficulty" => "Cycle the difficulty used by this roster.",
            "AiRosterCount" => "Number of bots requested for this roster.",
            "AiRosterSquadId" => "Squad identifier used to group bots in this roster.",
            "AiRosterSpawnNext" => "Select a spawn point to add or remove its roster assignment.",
            "AiRosterSpawnPoints" => "Assigned spawn point identifiers. Use the selector above to choose existing points.",
            "AiRosterPatrolNext" => "Assign an existing patrol route to the roster.",
            "AiRosterPatrolRoute" => "Assigned patrol route identifier. Use the selector above to choose a route.",
            "AiPace" => "Cycle the movement pace along the patrol route.",
            "AiCompletion" => "Cycle what bots do after reaching the end of the patrol route.",
            "AiWaypointWaitSeconds" => "Time spent waiting at this waypoint, in seconds.",
            "ContainerMode" => "Choose how this container's contents are generated.",
            "ContainerPool" => "Choose the loot pool used to generate this container's contents.",
            "ContainerChance" => "Chance of spawning contents, from 0 to 100 percent.",
            "ContainerSearch" => "Search for items to add to the container's fixed contents.",
            "ContainerItem" => "Choose an item from the search results.",
            "ContainerQuantity" => "Quantity to add to the fixed contents.",
            "ContainerAdd" => "Add the selected item and quantity to this container.",
            "ContainerContents" => "Select an existing fixed-content entry to inspect or remove.",
            "ContainerRemove" => "Remove the selected entry from this container's fixed contents.",
            "ContainerLock" => "Toggle whether the container is locked.",
            "ContainerKeySearch" => "Search for a key to unlock this container.",
            "ContainerKeyItem" => "Choose a key from the search results.",
            "ContainerUseKey" => "Assign the selected key to this container's lock.",
            "EnvironmentHour" => "Preview time in 24-hour HH:mm format. Select Set time to apply.",
            "EnvironmentApply" => "Apply the entered time to the editor preview.",
            "EnvironmentEarlier" => "Move the preview clock back one hour.",
            "EnvironmentLater" => "Move the preview clock forward one hour.",
            "EnvironmentReset" => "Restore the raid's original time in the preview.",
            "EnvironmentDawn" or "EnvironmentNoon" or "EnvironmentDusk" or "EnvironmentNight" => "Preview the map at "
                + caption.ToLowerInvariant()
                + ".",
            "WeatherPresetClear" or "WeatherPresetCloudy" or "WeatherPresetRain" or "WeatherPresetStorm" => "Apply the "
                + caption.ToLowerInvariant()
                + " weather preset to the preview.",
            "WeatherClouds" or "WeatherRain" or "WeatherFog" or "WeatherWind" or "WeatherThunder" =>
                "Preview intensity from 0 to 100 percent. Select Apply weather to apply.",
            "WeatherDirection" => "Cycle the wind direction used by the weather preview.",
            "WeatherApply" => "Apply the entered weather values to the editor preview.",
            "WeatherReset" => "Restore the raid's original weather in the preview.",
            _ when id.StartsWith("MapPosition") || id.StartsWith("Position") => caption + " position in world metres.",
            _ when id.StartsWith("MapRotation") || id.StartsWith("Rotation") => caption + " rotation in degrees.",
            _ when id.StartsWith("MapSize") => caption + " size or scale for the selected object or volume.",
            _ when id.StartsWith("Size") => caption + " dimension in metres.",
            _ => caption,
        };
}
