<Project>
  <Import
    Project="$(MSBuildThisFileDirectory)Directory.Build.local.props"
    Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')"
  />
  <PropertyGroup>
    <Version>0.5.2</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TarkovDir Condition="'$(TarkovDir)' == ''">$(MSBuildThisFileDirectory)..\..\</TarkovDir>
    <ManagedDir Condition="'$(ManagedDir)' == ''">$(TarkovDir)EscapeFromTarkov_Data\Managed\</ManagedDir>
    <ServerDir Condition="'$(ServerDir)' == ''">$(TarkovDir)SPT_Runtime\</ServerDir>
    <SeasonalAssetsDir Condition="'$(SeasonalAssetsDir)' == ''"
      >$(MSBuildThisFileDirectory)..\CJ-SDK\Assets\Mods\SeasonalPerks.Assets\</SeasonalAssetsDir>
    <SeasonalClientDir>$(TarkovDir)BepInEx\plugins\SeasonalPerks\</SeasonalClientDir>
    <SeasonalServerDir>$(ServerDir)user\mods\SeasonalPerks\</SeasonalServerDir>
    <SeasonalBackupDir Condition="'$(SeasonalBackupDir)' == ''">$(MSBuildThisFileDirectory)artifacts\install-backups\</SeasonalBackupDir>
  </PropertyGroup>
</Project>
