<Project>
  <Import
    Project="$(MSBuildThisFileDirectory)Directory.Build.local.props"
    Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')"
  />
  <PropertyGroup>
    <Version>0.7.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TarkovDir Condition="'$(TarkovDir)' == ''">$(MSBuildThisFileDirectory)..\..\</TarkovDir>
    <ManagedDir Condition="'$(ManagedDir)' == ''">$(TarkovDir)EscapeFromTarkov_Data\Managed\</ManagedDir>
    <ServerDir Condition="'$(ServerDir)' == ''">$(TarkovDir)SPT_Runtime\</ServerDir>
    <CampaignsAssetsDir Condition="'$(CampaignsAssetsDir)' == ''"
      >$(MSBuildThisFileDirectory)..\CJ-SDK\Assets\Mods\WTT-Campaigns.Assets\</CampaignsAssetsDir>
    <CampaignsClientDir>$(TarkovDir)BepInEx\plugins\WTT-Campaigns\</CampaignsClientDir>
    <CampaignsServerDir>$(ServerDir)user\mods\WTT-Campaigns\</CampaignsServerDir>
    <CampaignsBackupDir Condition="'$(CampaignsBackupDir)' == ''">$(MSBuildThisFileDirectory)artifacts\install-backups\</CampaignsBackupDir>
  </PropertyGroup>
</Project>
