using UnityEngine;
using UnityEngine.EventSystems;
using WTT.Campaigns.Client.Spatial;
using WTT.Campaigns.UI.Controls;

namespace WTT.Campaigns.Client.Authoring;

public sealed partial class RaidEditor
{
    private EditorCameraGesture _cameraGesture;
    private Vector3 _navigationPivot;
    private int _navigationStarted;
    private readonly EditorPointerCapture _pointerCapture = new();

    private bool CaptureCameraGesture()
    {
        var next = EditorCameraGesturePolicy.Resolve(
            _cameraGesture,
            _open
                && Application.isFocused
                && _view?.Typing != true
                && _drag == null
                && _session?.Conflict == null
                && _view?.Windows.HasMenu != true,
            EventSystem.current?.IsPointerOverGameObject() != true && _view?.PointerOver == false,
            Input.GetMouseButton(1),
            Input.GetMouseButton(2),
            Input.GetMouseButton(0),
            Input.GetKey(KeyCode.LeftAlt) || Input.GetKey(KeyCode.RightAlt)
        );
        if (next != EditorCameraGesture.None)
        {
            _pointerCapture.Remember();
            if (next != _cameraGesture)
            {
                _navigationStarted = Time.frameCount;
                _navigationPivot =
                    TrySelectionBounds(out var bounds) ? bounds.center
                    : Selected is { } selected ? ZoneRuntime.Vector(selected.Position)
                    : _flyPosition + _flyRotation * Vector3.forward * 10;
                if (Vector3.Distance(_navigationPivot, _flyPosition) < .5f)
                    _navigationPivot = _flyPosition + _flyRotation * Vector3.forward * .5f;
            }
        }
        _cameraGesture = next;
        return _looking = next != EditorCameraGesture.None;
    }

    private void NavigateCamera()
    {
        if (Time.frameCount == _navigationStarted)
            return; // Ignore the input delta generated by locking the pointer.
        var x = Input.GetAxis("Mouse X");
        var y = Input.GetAxis("Mouse Y");
        if (_cameraGesture == EditorCameraGesture.Orbit)
        {
            var offset = Quaternion.AngleAxis(x * 2, Vector3.up) * (_flyPosition - _navigationPivot);
            var elevation = Mathf.Asin(Mathf.Clamp(offset.normalized.y, -1, 1)) * Mathf.Rad2Deg;
            var pitch = Mathf.Clamp(elevation - y * 2, -89, 89) - elevation;
            var right = Vector3.Cross(Vector3.up, -offset.normalized);
            if (right.sqrMagnitude < .0001f)
                right = _flyRotation * Vector3.right;
            offset = Quaternion.AngleAxis(pitch, right.normalized) * offset;
            _flyPosition = _navigationPivot + offset;
            _flyRotation = Quaternion.LookRotation(-offset, Vector3.up);
        }
        else if (_cameraGesture == EditorCameraGesture.Pan)
        {
            var distance = Mathf.Max(.5f, Vector3.Distance(_flyPosition, _navigationPivot));
            var worldPerPixel =
                2 * distance * Mathf.Tan(_camera!.fieldOfView * Mathf.Deg2Rad / 2) / Mathf.Max(1, SceneViewport.ScreenRect(_camera).height);
            var delta = -(_flyRotation * new Vector3(x, y, 0)) * (10 * worldPerPixel);
            _flyPosition += delta;
            _navigationPivot += delta;
        }
        else
        {
            var angles = _flyRotation.eulerAngles;
            angles.x -= y * 2;
            angles.y += x * 2;
            _flyRotation = Quaternion.Euler(angles);
            var direction = new Vector3(
                (Input.GetKey(KeyCode.D) ? 1 : 0) - (Input.GetKey(KeyCode.A) ? 1 : 0),
                0,
                (Input.GetKey(KeyCode.W) ? 1 : 0) - (Input.GetKey(KeyCode.S) ? 1 : 0)
            );
            direction = _flyRotation * direction;
            direction.y += (Input.GetKey(KeyCode.E) ? 1 : 0) - (Input.GetKey(KeyCode.Q) ? 1 : 0);
            _flyPosition +=
                Vector3.ClampMagnitude(direction, 1)
                * Time.unscaledDeltaTime
                * CameraSpeed
                * (
                    Input.GetKey(KeyCode.LeftShift) ? 4
                    : Input.GetKey(KeyCode.LeftControl) ? .25f
                    : 1
                );
        }
    }
}
