using Mono.Cecil;
using Mono.Cecil.Cil;

namespace WTT.Campaigns.Tests;

internal static class AiControlsChecks
{
    private static readonly string[] ExpectedActionGroups =
    {
        "AiTriggerGroup",
        "AiWaveWaitPreviousGroup",
        "AiRosterRoleGroup",
        "AiRosterDifficultyGroup",
        "AiRosterSpawnNextGroup",
        "AiRosterPatrolNextGroup",
        "AiPaceGroup",
        "AiCompletionGroup",
    };

    internal static void Run(AssemblyDefinition assembly, Action<bool, string> check)
    {
        var view = assembly.MainModule.GetType("WTT.Campaigns.Client.Authoring.RaidEditorAiView");
        var editor = assembly.MainModule.GetType("WTT.Campaigns.Client.Authoring.RaidEditor");
        var prepare = Method(view, "Prepare");
        var refresh = Method(editor, "RefreshAiWorkspace");
        var bind = Method(editor, "BindAiControls");

        var generated = GeneratedControls(prepare);
        var generatedGroups = generated.Groups;
        var generatedButtons = generated.Buttons;
        var generatedFields = generated.Fields;

        check(
            ExpectedActionGroups.All(generatedGroups.Contains),
            "AI action controls are wrapped in the inspector groups consumed by refresh"
        );

        var consumedGroups = StringOperands(refresh)
            .Where(name => name.StartsWith("Ai", StringComparison.Ordinal) && name.EndsWith("Group", StringComparison.Ordinal))
            .ToHashSet(StringComparer.Ordinal);
        check(consumedGroups.SetEquals(generatedGroups), "Every AI inspector group consumed by refresh is generated by Prepare");

        var boundButtons = CallArguments(bind, "Button")
            .Where(name => name.StartsWith("Ai", StringComparison.Ordinal))
            .ToHashSet(StringComparer.Ordinal);
        check(generatedButtons.SetEquals(boundButtons), "Every AI button generated by Prepare is bound by BindAiControls");

        var boundFields = CallArguments(bind, "Input")
            .Where(name => name.StartsWith("Ai", StringComparison.Ordinal))
            .ToHashSet(StringComparer.Ordinal);
        check(generatedFields.SetEquals(boundFields), "Every AI input generated by Prepare is bound by BindAiControls");

        foreach (var helperName in new[] { "Add", "AddField", "AddAction" })
        {
            var helper = Method(view, helperName);
            check(
                helper.Body.Instructions.Any(IsInactiveSetActive),
                "AI " + helperName + " controls start hidden until the active workspace presents them"
            );
        }

        foreach (var fieldName in new[] { "CreationControls", "InspectorGroups", "InspectorFields" })
        {
            check(
                refresh.Body.Instructions.Any(i => i.Operand is FieldReference field && field.Name == fieldName),
                "Leaving AI refreshes and hides the complete " + fieldName + " inventory"
            );
        }

        var workspace = Method(editor, "RefreshWorkspace");
        var presentIndex = workspace
            .Body.Instructions.Select((instruction, index) => (instruction, index))
            .First(pair => pair.instruction.Operand is MethodReference method && method.Name == "Present")
            .index;
        var windowsIndex = workspace
            .Body.Instructions.Select((instruction, index) => (instruction, index))
            .Take(presentIndex)
            .Last(pair => pair.instruction.Operand is FieldReference field && field.Name == "Windows")
            .index;
        var modeLoad = workspace.Body.Instructions.Skip(windowsIndex + 1).Take(3).ToArray();
        check(
            modeLoad.Length == 3
                && modeLoad[0].OpCode == OpCodes.Ldarg_0
                && modeLoad[1].Operand is FieldReference mode
                && mode.Name == "_mode"
                && modeLoad[2].OpCode != OpCodes.Ldstr,
            "AI workspace presents the native AI category instead of routing it through Captures"
        );
    }

    private static MethodDefinition Method(TypeDefinition? type, string name)
    {
        if (type == null)
            throw new InvalidOperationException("The compiled client is missing the AI control type.");
        return type.Methods.Single(method => method.Name == name);
    }

    private static IEnumerable<string> StringOperands(MethodDefinition method) =>
        method.Body.Instructions.Where(instruction => instruction.Operand is string).Select(instruction => (string)instruction.Operand);

    private static HashSet<string> CallArguments(MethodDefinition method, string callName)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        var instructions = method.Body.Instructions;
        for (var index = 0; index < instructions.Count; index++)
        {
            if (instructions[index].Operand is not MethodReference call || call.Name != callName)
                continue;
            var literal = PreviousString(instructions, index);
            if (literal != null)
                result.Add(literal);
        }
        return result;
    }

    private static (HashSet<string> Buttons, HashSet<string> Groups, HashSet<string> Fields) GeneratedControls(MethodDefinition prepare)
    {
        var buttons = new HashSet<string>(StringComparer.Ordinal);
        var groups = new HashSet<string>(StringComparer.Ordinal);
        var fields = new HashSet<string>(StringComparer.Ordinal);
        var instructions = prepare.Body.Instructions;
        for (var index = 0; index < instructions.Count; index++)
        {
            if (instructions[index].Operand is not MethodReference call)
                continue;
            if (call.Name == "Add")
            {
                var name = PreviousStrings(instructions, index, 2).FirstOrDefault();
                if (name != null)
                    buttons.Add(name);
            }
            else if (call.Name == "AddField")
            {
                var name = PreviousStrings(instructions, index, 2).FirstOrDefault();
                if (name != null)
                {
                    fields.Add(name);
                    groups.Add(name + "Group");
                }
            }
            else if (call.Name == "AddAction")
            {
                var arguments = PreviousStrings(instructions, index, 3).ToArray();
                if (arguments.Length == 3)
                {
                    groups.Add(arguments[0]);
                    buttons.Add(arguments[1]);
                }
            }
        }
        return (buttons, groups, fields);
    }

    private static string? PreviousString(Mono.Collections.Generic.Collection<Instruction> instructions, int index)
    {
        for (var i = index - 1; i >= 0 && index - i <= 8; i--)
            if (instructions[i].Operand is string value)
                return value;
        return null;
    }

    private static IEnumerable<string> PreviousStrings(Mono.Collections.Generic.Collection<Instruction> instructions, int index, int count)
    {
        var values = new List<string>();
        for (var i = index - 1; i >= 0 && index - i <= 12 && values.Count < count; i--)
            if (instructions[i].Operand is string value)
                values.Add(value);
        values.Reverse();
        return values;
    }

    private static bool IsInactiveSetActive(Instruction instruction)
    {
        if (instruction.Operand is not MethodReference method || method.Name != "SetActive")
            return false;
        return instruction.Previous?.OpCode == OpCodes.Ldc_I4_0;
    }
}
