<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../Server/WTT-Seasonal.Server.csproj" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.0" />
  </ItemGroup>
</Project>
