<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);BL0006</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Server\WTT-Campaigns.Server.csproj" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.1.0" />
  </ItemGroup>
</Project>
