"""Expose the exact client view sources to the SDK's preview assemblies.

Unity 2022 supports C# 9. The only syntax conversion is file-scoped namespaces.
The pointer component compiles outside Editor so Unity can attach it in previews.
Generated sources are never dependencies of the UI asset bundle.
"""
from pathlib import Path
import re

project = Path(__file__).resolve().parents[1]
target = project.parent / 'CJ-SDK/Assets/Mods/SeasonalPerks.Assets/Editor/Generated'
target.mkdir(parents=True, exist_ok=True)
runtime = target.parents[1] / 'PreviewRuntime'
runtime.mkdir(parents=True, exist_ok=True)
for source in (project / 'UI').glob('*.cs'):
    text = source.read_text(encoding='utf-8-sig')
    text = re.sub(r'namespace SeasonalPerks.UI;', 'namespace SeasonalPerks.UI\n{', text) + '\n}\n'
    destination = runtime if source.name in ['PerkPointer.cs', 'ProfileCardHover.cs', 'UiButtonFeedback.cs', 'InterfaceSound.cs', 'PerkCardHover.cs'] else target
    (destination / source.name).write_text('// Generated by SeasonalPerks/tools/sync_ui_preview.py. Edit the UI project source.\n#nullable enable\n' + text, encoding='utf-8')
print('Synchronized UI view sources for the Unity editor preview.')
