"""Expose the exact client view sources to the SDK's preview assemblies.

Unity 2022 supports C# 9. The only syntax conversion is file-scoped namespaces.
The pointer component compiles outside Editor so Unity can attach it in previews.
Generated sources are never dependencies of the UI asset bundle.
"""
from pathlib import Path
import re

RUNTIME_SOURCES = {
    'EditorWindowDrag.cs',
    'RaidEditorWindows.cs',
    'CampaignBranding.cs',
    'StoryTitleMask.cs',
    'StoryRoomAmbient.cs',
    'StoryRoomRenderState.cs',
    'StoryRoomIsolation.cs',
    'StoryVisitButton.cs',
    'StoryTradeTabRow.cs',
    'StoryUiArtwork.cs',
    'StoryEnvironmentState.cs',
    'StoryRoomLighting.cs',
    'HubPointer.cs',
    'SeasonBanner.cs',
    'UiElements.cs',
    'PerkPointer.cs',
    'ProfileCardHover.cs',
    'ProfileCarousel.cs',
    'ProfileCardPreview.cs',
    'UiButtonFeedback.cs',
    'InterfaceSound.cs',
    'PerkCardHover.cs',
}


def sync_sources(source_root: Path, target: Path, runtime: Path) -> int:
    generated = {}
    for source in sorted(source_root.rglob('*.cs')):
        if any(part.lower() in {'bin', 'obj'} for part in source.relative_to(source_root).parts):
            continue
        text = source.read_text(encoding='utf-8-sig')
        text, count = re.subn(
            r'^namespace (WTT\.Campaigns\.UI(?:\.\w+)*);$',
            r'namespace \1\n{',
            text,
            flags=re.MULTILINE,
        )
        if count != 1:
            raise ValueError(f'Expected one UI file-scoped namespace in {source}')
        # Preserve existing generated filenames and Unity .meta GUIDs when source folders move.
        if source.name in generated:
            raise ValueError(f'Duplicate UI source filename: {source.name}')
        destination = runtime if source.name in RUNTIME_SOURCES else target
        generated[source.name] = (destination / source.name, text + '\n}\n')

    for destination, text in generated.values():
        destination.parent.mkdir(parents=True, exist_ok=True)
        # A shared helper can move into PreviewRuntime when a new component needs it.
        # Move its existing metadata as well, preserving the asset GUID.
        other = (runtime if destination.parent == target else target) / destination.name
        if other.exists():
            if not other.read_text(encoding='utf-8-sig').startswith('// Generated by SeasonalPerks/tools/sync_ui_preview.py.'):
                raise ValueError(f'Refusing to move non-generated source: {other}')
            old_meta = other.with_suffix(other.suffix + '.meta')
            new_meta = destination.with_suffix(destination.suffix + '.meta')
            if old_meta.exists() and not new_meta.exists():
                old_meta.rename(new_meta)
            other.unlink()
        destination.write_text(
            '// Generated by SeasonalPerks/tools/sync_ui_preview.py. Edit the UI project source.\n'
            '#nullable enable\n' + text,
            encoding='utf-8',
        )
    return len(generated)


if __name__ == '__main__':
    project = Path(__file__).resolve().parents[1]
    assets = project.parent / 'CJ-SDK/Assets/Mods/WTT-Campaigns.Assets'
    count = sync_sources(project / 'UI', assets / 'Editor/Generated', assets / 'PreviewRuntime')
    builder = 'CampaignsRaidEditorBuilder.cs'
    (assets / 'Editor' / builder).write_text((project / 'tools/unity' / builder).read_text(encoding='utf-8'), encoding='utf-8')
    legacy = assets / 'Editor/SeasonalRaidEditorBuilder.cs'
    if legacy.exists():
        legacy.write_text('// Legacy SDK entry point. Implementation lives in SeasonalPerks/tools/unity.\n'
                          'public static class SeasonalRaidEditorBuilder {\n'
                          '    public static void Build() => CampaignsRaidEditorBuilder.Build();\n'
                          '    public static void Preview() => CampaignsRaidEditorBuilder.Preview();\n}\n', encoding='utf-8')
    # Pure presentation copy is shared with the server, and compiled directly by Unity previews.
    presentation = (project / 'Shared/Presentation/CampaignText.cs').read_text(encoding='utf-8-sig')
    presentation = presentation.replace('namespace WTT.Campaigns.Shared.Presentation;', 'namespace WTT.Campaigns.Shared.Presentation\n{') + '\n}\n'
    (assets / 'PreviewRuntime/CampaignText.cs').write_text(presentation, encoding='utf-8')
    print(f'Synchronized {count} UI view sources for the Unity editor preview.')
