"""Expose the exact client view sources to the SDK's preview assemblies.

Unity 2022 supports C# 9. The only syntax conversion is file-scoped namespaces.
The pointer component compiles outside Editor so Unity can attach it in previews.
Generated sources are never dependencies of the UI asset bundle.
"""
from pathlib import Path
import re

RUNTIME_SOURCES = {
    'EditorMaterialArtwork.cs',
    'EditorWindowLayout.cs',
    'SceneHandleMath.cs',
    'SceneSelectionGeometry.cs',
    'CampaignBranding.cs',
    'StoryTitleMask.cs',
    'StoryRoomAmbient.cs',
    'StoryRoomRenderState.cs',
    'StoryRoomIsolation.cs',
    'StoryVisitButton.cs',
    'StoryTradeTabRow.cs',
    'StoryUiArtwork.cs',
    'StoryEnvironmentState.cs',
    'StoryRoomLighting.cs',
    'HubPointer.cs',
    'SeasonBanner.cs',
    'UiElements.cs',
    'PerkPointer.cs',
    'ProfileCardHover.cs',
    'ProfileCarousel.cs',
    'ProfileCardPreview.cs',
    'UiButtonFeedback.cs',
    'InterfaceSound.cs',
    'PerkCardHover.cs',
}


def sync_sources(source_root: Path, target: Path, runtime: Path) -> int:
    # Remove only our generated helpers retired by the Tarkov tool-window migration.
    for retired in ['EditorMaterialTheme.cs', 'EditorTarkovTheme.cs', 'EditorWindowResize.cs', 'EditorWindowFocus.cs', 'RaidEditorWindows.Layout.cs', 'EditorWindowDrag.cs', 'EditorRowSelection.cs', 'EditorControlTooltip.cs', 'RaidEditorWindows.cs', 'EditorTreeView.cs', 'EditorDropdown.cs', 'RaidEditorLayout.cs', 'RaidEditorLayout.Navigation.cs', 'RaidEditorLayout.Tools.cs', 'RaidEditorLayout.Environment.cs', 'EditorHomeLayout.cs']:
        for folder in [target, runtime]:
            old = folder / retired
            if old.exists() and old.read_text(encoding='utf-8-sig').startswith('// Generated by SeasonalPerks/tools/sync_ui_preview.py.'):
                old.unlink()
                old.with_suffix(old.suffix + '.meta').unlink(missing_ok=True)
    generated = {}
    for source in sorted(source_root.rglob('*.cs')):
        if any(part.lower() in {'bin', 'obj'} for part in source.relative_to(source_root).parts):
            continue
        text = source.read_text(encoding='utf-8-sig')
        text, count = re.subn(
            r'^namespace (WTT\.Campaigns\.UI(?:\.\w+)*);$',
            r'namespace \1\n{',
            text,
            flags=re.MULTILINE,
        )
        if count != 1:
            raise ValueError(f'Expected one UI file-scoped namespace in {source}')
        # Preserve existing generated filenames and Unity .meta GUIDs when source folders move.
        if source.name in generated:
            raise ValueError(f'Duplicate UI source filename: {source.name}')
        destination = runtime if source.name in RUNTIME_SOURCES else target
        generated[source.name] = (destination / source.name, text + '\n}\n')

    for destination, text in generated.values():
        destination.parent.mkdir(parents=True, exist_ok=True)
        # A shared helper can move into PreviewRuntime when a new component needs it.
        # Move its existing metadata as well, preserving the asset GUID.
        other = (runtime if destination.parent == target else target) / destination.name
        if other.exists():
            if not other.read_text(encoding='utf-8-sig').startswith('// Generated by SeasonalPerks/tools/sync_ui_preview.py.'):
                raise ValueError(f'Refusing to move non-generated source: {other}')
            old_meta = other.with_suffix(other.suffix + '.meta')
            new_meta = destination.with_suffix(destination.suffix + '.meta')
            if old_meta.exists() and not new_meta.exists():
                old_meta.rename(new_meta)
            other.unlink()
        destination.write_text(
            '// Generated by SeasonalPerks/tools/sync_ui_preview.py. Edit the UI project source.\n'
            '#nullable enable\n' + text,
            encoding='utf-8',
        )
    return len(generated)


if __name__ == '__main__':
    project = Path(__file__).resolve().parents[1]
    assets = project.parent / 'CJ-SDK/Assets/Mods/WTT-Campaigns.Assets'
    count = sync_sources(project / 'UI', assets / 'Editor/Generated', assets / 'PreviewRuntime')
    (assets / 'RaidEditor/CampaignScenePreview.shader').write_text((project / 'tools/unity/CampaignScenePreview.shader').read_text(encoding='utf-8'), encoding='utf-8')
    for helper in ['ScenePicking.cs', 'ScenePropSupport.cs', 'SceneBodyState.cs']:
        picking = (project / 'Client/Authoring/Scenes' / helper).read_text(encoding='utf-8').replace('namespace WTT.Campaigns.Client.Authoring.Scenes;', 'namespace WTT.Campaigns.Client.Authoring.Scenes\n{') + '\n}\n'
        (assets / 'Editor' / helper).write_text('#nullable enable\n' + picking, encoding='utf-8')
    builder = 'CampaignsEditorToolkitBuilder.cs'
    (assets / 'Editor' / builder).write_text((project / 'tools/unity' / builder).read_text(encoding='utf-8'), encoding='utf-8')
    for name in ['CampaignsRaidEditorBuilder.cs', 'SeasonalRaidEditorBuilder.cs']:
        retired = assets / 'Editor' / name
        if retired.exists():
            content = retired.read_text(encoding='utf-8-sig')
            if 'CampaignsRaidEditorBuilder' not in content:
                raise ValueError(f'Refusing to remove unrecognized SDK builder: {retired}')
            retired.unlink()
            retired.with_suffix('.cs.meta').unlink(missing_ok=True)
    # Pure presentation copy is shared with the server, and compiled directly by Unity previews.
    presentation = (project / 'Shared/Presentation/CampaignText.cs').read_text(encoding='utf-8-sig')
    presentation = presentation.replace('namespace WTT.Campaigns.Shared.Presentation;', 'namespace WTT.Campaigns.Shared.Presentation\n{') + '\n}\n'
    (assets / 'PreviewRuntime/CampaignText.cs').write_text(presentation, encoding='utf-8')
    print(f'Synchronized {count} UI view sources for the Unity editor preview.')
